### Import Dependencies

In [2]:
import openai
import pandas as pd
import tiktoken


from qdrant_client import QdrantClient
from qdrant_client import models
from qdrant_client.models import FieldCondition, MatchAny, Filter
from qdrant_client.models import VectorParams, Distance, SparseVectorParams, Modifier, PayloadSchemaType, PointStruct, Document, Prefetch, FusionQuery

### Create Qdrant collection for hybrid search

In [3]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [4]:
qdrant_client.create_collection(
    collection_name="Amazon-reviews-collection-01",
    vectors_config={
        "text-embedding-3-small": VectorParams(size=1536, distance=Distance.COSINE)
    }
)

True

In [5]:
qdrant_client.create_payload_index(
    collection_name="Amazon-reviews-collection-01",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

### Embedding Functions

In [6]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [7]:
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i + batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    
    return all_embeddings

### Read the sampled dataset with Amazon inventory data
- useful information can both from title and text, so concat it together

In [11]:
df_reviews = pd.read_json("../../data/raw/Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [12]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5,Love it! It fits my Chromebook perfectly,Love it! It fits my Chromebook perfectly.,[],B00J39BYSG,B07BJ8KD6X,AHSPLDNW5OOUK2PLH7GXLACFBZNQ,2015-06-30 21:27:51.000,0,True
1,5,love this,i was concerned it wasnt gonna work with my TV...,[],B008GVOVK0,B008GVOVK0,AHGAOIZVODNHYMNCBV4DECZH42UQ,2018-08-24 22:21:36.983,0,True
2,5,nice product,adjustable and elastic,[],B01G54B68Y,B07HMRN7Y6,AGEP2CC2QIJU5IHQZXCC7BE5JSDQ,2019-11-12 17:33:07.317,0,True
3,4,Satisfied,Works well,[],B019WJROSK,B019WJROSK,AHSAUHUTLVNKJ72GUIPGI5XZH6ZA,2019-02-01 20:54:53.408,0,True
4,5,Works great,This wire works great. I recommend it. It's ...,[],B08G8PMN8C,B08J42GSW6,AHATA6X6MYTC3VNBFJ3WIYVK257A,2021-02-25 01:59:27.685,0,False

In [13]:
def preprocess_reviews_data(row):
    return f"{row['title']} {row['text']}"

In [21]:
def count_tokens(row):

    encoding = tiktoken.encoding_for_model("text-embedding-3-small")

    return len(encoding.encode(row["preprocessed_data"]))

In [22]:
count_tokens({"preprocessed_data": "How are you doing today?"})

6

In [23]:
df_reviews["preprocessed_data"] = df_reviews.apply(preprocess_reviews_data, axis=1)
df_reviews["token_count"] = df_reviews.apply(count_tokens, axis=1)

In [28]:
len(df_reviews), len(df_reviews[df_reviews["token_count"] < 8192])

(137987, 137987)

In [ ]:
df_reviews = df_reviews[df_reviews["token_count"] < 8192] # only embedding model can only take 8192 tokens

In [29]:
total_tokens = df_reviews["token_count"].sum()
total_tokens

np.int64(8247850)

### Embed the text and add additional fields to the payload of each vector for reviews

In [33]:
df_data_to_embed = df_reviews[["preprocessed_data", "parent_asin"]].copy()
data_to_embed_reviews = df_data_to_embed.to_dict(orient="records")
text_to_embed_reviews = [item["preprocessed_data"] for item in data_to_embed_reviews]
embeddings = get_embeddings_batch(text_to_embed_reviews, batch_size=500)

Processed 500 of 137987
Processed 1000 of 137987
Processed 1500 of 137987
Processed 2000 of 137987
Processed 2500 of 137987
Processed 3000 of 137987
Processed 3500 of 137987
Processed 4000 of 137987
Processed 4500 of 137987
Processed 5000 of 137987
Processed 5500 of 137987
Processed 6000 of 137987
Processed 6500 of 137987
Processed 7000 of 137987
Processed 7500 of 137987
Processed 8000 of 137987
Processed 8500 of 137987
Processed 9000 of 137987
Processed 9500 of 137987
Processed 10000 of 137987
Processed 10500 of 137987
Processed 11000 of 137987
Processed 11500 of 137987
Processed 12000 of 137987
Processed 12500 of 137987
Processed 13000 of 137987
Processed 13500 of 137987
Processed 14000 of 137987
Processed 14500 of 137987
Processed 15000 of 137987
Processed 15500 of 137987
Processed 16000 of 137987
Processed 16500 of 137987
Processed 17000 of 137987
Processed 17500 of 137987
Processed 18000 of 137987
Processed 18500 of 137987
Processed 19000 of 137987
Processed 19500 of 137987
Processed 20000 of 137987
Processed 20500 of 137987
Processed 21000 of 137987
Processed 21500 of 137987
Processed 22000 of 137987
Processed 22500 of 137987
Processed 23000 of 137987
Processed 23500 of 137987
Processed 24000 of 137987
Processed 24500 of 137987
Processed 25000 of 137987
Processed 25500 of 137987
Processed 26000 of 137987
Processed 26500 of 137987
Processed 27000 of 137987
Processed 27500 of 137987
Processed 28000 of 137987
Processed 28500 of 137987
Processed 29000 of 137987
Processed 29500 of 137987
Processed 30000 of 137987
Processed 30500 of 137987
Processed 31000 of 137987
Processed 31500 of 137987
Processed 32000 of 137987
Processed 32500 of 137987
Processed 33000 of 137987
Processed 33500 of 137987
Processed 34000 of 137987
Processed 34500 of 137987
Processed 35000 of 137987
Processed 35500 of 137987
Processed 36000 of 137987
Processed 36500 of 137987
Processed 37000 of 137987
Processed 37500 of 137987
Processed 38000 of 137987
Processed 38500 of 137987
Processed 39000 of 137987
Processed 39500 of 137987
Processed 40000 of 137987
Processed 40500 of 137987
Processed 41000 of 137987
Processed 41500 of 137987
Processed 42000 of 137987
Processed 42500 of 137987
Processed 43000 of 137987
Processed 43500 of 137987
Processed 44000 of 137987
Processed 44500 of 137987
Processed 45000 of 137987
Processed 45500 of 137987
Processed 46000 of 137987
Processed 46500 of 137987
Processed 47000 of 137987
Processed 47500 of 137987
Processed 48000 of 137987
Processed 48500 of 137987
Processed 49000 of 137987
Processed 49500 of 137987
Processed 50000 of 137987
Processed 50500 of 137987
Processed 51000 of 137987
Processed 51500 of 137987
Processed 52000 of 137987
Processed 52500 of 137987
Processed 53000 of 137987
Processed 53500 of 137987
Processed 54000 of 137987
Processed 54500 of 137987
Processed 55000 of 137987
Processed 55500 of 137987
Processed 56000 of 137987
Processed 56500 of 137987
Processed 57000 of 137987
Processed 57500 of 137987
Processed 58000 of 137987
Processed 58500 of 137987
Processed 59000 of 137987
Processed 59500 of 137987
Processed 60000 of 137987
Processed 60500 of 137987
Processed 61000 of 137987
Processed 61500 of 137987
Processed 62000 of 137987
Processed 62500 of 137987
Processed 63000 of 137987
Processed 63500 of 137987
Processed 64000 of 137987
Processed 64500 of 137987
Processed 65000 of 137987
Processed 65500 of 137987
Processed 66000 of 137987
Processed 66500 of 137987
Processed 67000 of 137987
Processed 67500 of 137987
Processed 68000 of 137987
Processed 68500 of 137987
Processed 69000 of 137987
Processed 69500 of 137987
Processed 70000 of 137987
Processed 70500 of 137987
Processed 71000 of 137987
Processed 71500 of 137987
Processed 72000 of 137987
Processed 72500 of 137987
Processed 73000 of 137987
Processed 73500 of 137987
Processed 74000 of 137987
Processed 74500 of 137987
Processed 75000 of 137987
Processed 75500 of 137987
Processed 76000 of 137987
Processed 76500 of 137987
Processed 77000 of 137987
Processed 77500 of 137987
Processed 78000 of 137987
Processed 78500 of 137987
Processed 79000 of 137987
Processed 79500 of 137987
Processed 80000 of 137987
Processed 80500 of 137987
Processed 81000 of 137987
Processed 81500 of 137987
Processed 82000 of 137987
Processed 82500 of 137987
Processed 83000 of 137987
Processed 83500 of 137987
Processed 84000 of 137987
Processed 84500 of 137987
Processed 85000 of 137987
Processed 85500 of 137987
Processed 86000 of 137987
Processed 86500 of 137987
Processed 87000 of 137987
Processed 87500 of 137987
Processed 88000 of 137987
Processed 88500 of 137987
Processed 89000 of 137987
Processed 89500 of 137987
Processed 90000 of 137987
Processed 90500 of 137987
Processed 91000 of 137987
Processed 91500 of 137987
Processed 92000 of 137987
Processed 92500 of 137987
Processed 93000 of 137987
Processed 93500 of 137987
Processed 94000 of 137987
Processed 94500 of 137987
Processed 95000 of 137987
Processed 95500 of 137987
Processed 96000 of 137987
Processed 96500 of 137987
Processed 97000 of 137987
Processed 97500 of 137987
Processed 98000 of 137987
Processed 98500 of 137987
Processed 99000 of 137987
Processed 99500 of 137987
Processed 100000 of 137987
Processed 100500 of 137987
Processed 101000 of 137987
Processed 101500 of 137987
Processed 102000 of 137987
Processed 102500 of 137987
Processed 103000 of 137987
Processed 103500 of 137987
Processed 104000 of 137987
Processed 104500 of 137987
Processed 105000 of 137987
Processed 105500 of 137987
Processed 106000 of 137987
Processed 106500 of 137987
Processed 107000 of 137987
Processed 107500 of 137987
Processed 108000 of 137987
Processed 108500 of 137987
Processed 109000 of 137987
Processed 109500 of 137987
Processed 110000 of 137987
Processed 110500 of 137987
Processed 111000 of 137987
Processed 111500 of 137987
Processed 112000 of 137987
Processed 112500 of 137987
Processed 113000 of 137987
Processed 113500 of 137987
Processed 114000 of 137987
Processed 114500 of 137987
Processed 115000 of 137987
Processed 115500 of 137987
Processed 116000 of 137987
Processed 116500 of 137987
Processed 117000 of 137987
Processed 117500 of 137987
Processed 118000 of 137987
Processed 118500 of 137987
Processed 119000 of 137987
Processed 119500 of 137987
Processed 120000 of 137987
Processed 120500 of 137987
Processed 121000 of 137987
Processed 121500 of 137987
Processed 122000 of 137987
Processed 122500 of 137987
Processed 123000 of 137987
Processed 123500 of 137987
Processed 124000 of 137987
Processed 124500 of 137987
Processed 125000 of 137987
Processed 125500 of 137987
Processed 126000 of 137987
Processed 126500 of 137987
Processed 127000 of 137987
Processed 127500 of 137987
Processed 128000 of 137987
Processed 128500 of 137987
Processed 129000 of 137987
Processed 129500 of 137987
Processed 130000 of 137987
Processed 130500 of 137987
Processed 131000 of 137987
Processed 131500 of 137987
Processed 132000 of 137987
Processed 132500 of 137987
Processed 133000 of 137987
Processed 133500 of 137987
Processed 134000 of 137987
Processed 134500 of 137987
Processed 135000 of 137987
Processed 135500 of 137987
Processed 136000 of 137987
Processed 136500 of 137987
Processed 137000 of 137987
Processed 137500 of 137987
Processed 138000 of 137987

In [48]:
df_data_to_embed[df_data_to_embed.preprocessed_data.str.contains('bad')]

                                        preprocessed_data parent_asin
37      Best Headphones Best sounding headphones I use...  B00JB31OUW
48      Good Sounding, Poor Fitting (on me) I debated ...  B07PZQ8MKL
76      Other than that they are fine. nice picture Th...  B00V8FAWC2
94      Like this 180* design. I have only had it a da...  B088DC1KPP
160     the directions are pretty useless and I had to...  B000EHWCDW
...                                                   ...         ...
137845  Decent device, good sized ball, ok for noteboo...  B0038KLG5C
137846  Decent device, good sized ball, ok for noteboo...  B0038KLG5C
137890  BUY THE WARRANTY!!!!!! Good TV Picture, Though...  B0014175NE
137919  ... help at all and screw hole placements are ...  B012GPCLR6
137920  Nice solid case, but suffers from poor quality...  B012GPCLR6

[3381 rows x 2 columns]

In [34]:
len(embeddings)

137987

In [35]:
pointstructs = []
i=1
for embedding, data in zip(embeddings, data_to_embed_reviews):
    pointstructs.append(
        PointStruct(
            id=i,
            vector={
                "text-embedding-3-small": embedding # only use dense vector for embedding
            },
            payload=data
        )
    )
    i += 1

In [36]:
pointstructs[0].vector

{'text-embedding-3-small': [0.03839111328125,
  -0.040618896484375,
  -0.037200927734375,
  -0.028961181640625,
  -0.0009469985961914062,
  -0.07733154296875,
  -0.010284423828125,
  0.00091552734375,
  -0.046234130859375,
  0.0026798248291015625,
  -0.024322509765625,
  0.0256500244140625,
  -0.0278472900390625,
  0.007015228271484375,
  0.0472412109375,
  0.00269317626953125,
  -0.038177490234375,
  -0.0237884521484375,
  0.020416259765625,
  0.0257110595703125,
  -0.01316070556640625,
  0.03973388671875,
  0.015838623046875,
  -0.0316162109375,
  0.00476837158203125,
  -0.050811767578125,
  -0.02801513671875,
  0.0034656524658203125,
  0.0203704833984375,
  -0.054931640625,
  -0.0072174072265625,
  -0.02154541015625,
  -0.00518798828125,
  -0.05255126953125,
  -0.01490020751953125,
  -0.010528564453125,
  -0.00939178466796875,
  -0.026580810546875,
  -0.011566162109375,
  0.04901123046875,
  -0.0217742919921875,
  0.055511474609375,
  0.0880126953125,
  0.04998779296875,
  -0.08001708984375,
  -0.031707763671875,
  -0.001354217529296875,
  0.06475830078125,
  -0.014068603515625,
  0.01568603515625,
  -0.0491943359375,
  0.062225341796875,
  -0.0020084381103515625,
  0.0301971435546875,
  0.01485443115234375,
  0.028900146484375,
  -0.004360198974609375,
  0.032806396484375,
  0.0252838134765625,
  -0.0213623046875,
  0.00894927978515625,
  -0.0413818359375,
  -0.00934600830078125,
  0.028717041015625,
  0.0005640983581542969,
  -0.035003662109375,
  -0.009185791015625,
  -0.055877685546875,
  -0.0270538330078125,
  -0.06396484375,
  0.0029697418212890625,
  -0.022125244140625,
  -0.0699462890625,
  -0.03851318359375,
  -0.01885986328125,
  0.019866943359375,
  0.011749267578125,
  0.01110076904296875,
  0.03790283203125,
  -0.0013113021850585938,
  -0.036834716796875,
  -0.0003387928009033203,
  0.00811767578125,
  -0.02099609375,
  -0.055419921875,
  -0.00691986083984375,
  -0.01526641845703125,
  -0.00827789306640625,
  -0.055816650390625,
  -0.0172119140625,
  0.046539306640625,
  -0.0185546875,
  0.0308837890625,
  -0.0174407958984375,
  -0.0162811279296875,
  0.05694580078125,
  -0.07391357421875,
  0.0287322998046875,
  0.0262298583984375,
  0.036590576171875,
  0.038909912109375,
  -0.027679443359375,
  0.004608154296875,
  -0.0267486572265625,
  -0.010101318359375,
  0.01776123046875,
  0.0164031982421875,
  -0.03753662109375,
  -0.0189971923828125,
  -0.0190277099609375,
  -0.0762939453125,
  -0.0235137939453125,
  -0.0108642578125,
  0.0189971923828125,
  -0.027099609375,
  -0.037811279296875,
  0.02215576171875,
  0.007720947265625,
  -0.058685302734375,
  -0.021148681640625,
  -0.032135009765625,
  -0.002262115478515625,
  0.01340484619140625,
  -0.0433349609375,
  -0.01165771484375,
  0.01885986328125,
  -0.055328369140625,
  -0.01666259765625,
  -0.05810546875,
  -0.0114898681640625,
  -0.019683837890625,
  0.03076171875,
  0.0033435821533203125,
  -0.0277099609375,
  -0.018280029296875,
  0.048858642578125,
  -0.0286102294921875,
  -0.03948974609375,
  -0.040252685546875,
  -0.0209197998046875,
  -0.0200347900390625,
  -0.030426025390625,
  0.031707763671875,
  -0.0222320556640625,
  -0.0209197998046875,
  0.002956390380859375,
  -0.021240234375,
  0.0108184814453125,
  -0.0293731689453125,
  0.006378173828125,
  -0.018951416015625,
  0.001186370849609375,
  -0.064208984375,
  0.0146026611328125,
  -0.0098114013671875,
  -0.0143890380859375,
  0.0369873046875,
  0.0164337158203125,
  -0.01328277587890625,
  0.0217437744140625,
  0.036376953125,
  0.0012311935424804688,
  0.0032806396484375,
  -0.011474609375,
  0.01105499267578125,
  0.052001953125,
  -0.020416259765625,
  0.003459930419921875,
  -0.045440673828125,
  0.01251983642578125,
  0.0242156982421875,
  0.0103759765625,
  -0.03582763671875,
  0.0188140869140625,
  -0.0077056884765625,
  0.0056610107421875,
  0.012420654296875,
  -0.00435638427734375,
  -0.0012998580932617188,
  -0.0008091926574707031,
  -0.0355224609375,
  -0.0240478515625,
  0.0004374980926513672,
  0.006626129150390625,
  -0.0252227783203125,
  -0.027801513671875,
  0.0435791015625,
  -0.008697509765625,
  -0.0268096923828125,
  -0.0028057098388671875,
  -0.0226593017578125,
  0.018218994140625,
  0.0322265625,
  -0.03118896484375,
  -0.0394287109375,
  0.005413055419921875,
  0.01209259033203125,
  0.0176239013671875,
  -0.05523681640625,
  0.0161590576171875,
  0.0201263427734375,
  0.06048583984375,
  -0.0247955322265625,
  -0.032806396484375,
  0.00010991096496582031,
  -0.01027679443359375,
  -0.06817626953125,
  0.034210205078125,
  0.0006957054138183594,
  -0.004802703857421875,
  0.0316162109375,
  0.04150390625,
  -0.00495147705078125,
  0.0067596435546875,
  0.0283966064453125,
  -0.05474853515625,
  0.0263214111328125,
  -0.00991058349609375,
  0.00852203369140625,
  0.0039520263671875,
  -0.04437255859375,
  0.034942626953125,
  0.06640625,
  -0.0286102294921875,
  0.00249481201171875,
  0.0665283203125,
  0.018310546875,
  -0.04522705078125,
  -0.021392822265625,
  -0.003643035888671875,
  0.01496124267578125,
  0.0401611328125,
  -0.024169921875,
  0.0180511474609375,
  0.056549072265625,
  -0.007068634033203125,
  0.00278472900390625,
  -0.02203369140625,
  -0.0044708251953125,
  0.00848388671875,
  -0.06396484375,
  0.0295257568359375,
  -0.0003464221954345703,
  -0.0004165172576904297,
  0.01165771484375,
  -0.047882080078125,
  -0.038177490234375,
  -0.0167694091796875,
  -0.020843505859375,
  0.00862884521484375,
  0.02288818359375,
  0.05322265625,
  0.01282501220703125,
  -0.0168304443359375,
  0.037872314453125,
  -0.023040771484375,
  -0.029052734375,
  0.036651611328125,
  -0.016082763671875,
  -0.0021572113037109375,
  -0.032318115234375,
  -0.0308685302734375,
  -0.00778961181640625,
  -0.01287078857421875,
  0.055328369140625,
  0.00868988037109375,
  0.0050506591796875,
  -0.0101318359375,
  0.0063934326171875,
  0.032623291015625,
  0.06317138671875,
  -0.0123443603515625,
  0.0279388427734375,
  0.02734375,
  -0.0189208984375,
  -0.01605224609375,
  -0.0640869140625,
  0.021331787109375,
  -0.02166748046875,
  0.0106201171875,
  0.00897979736328125,
  0.013763427734375,
  0.01053619384765625,
  0.03509521484375,
  0.020355224609375,
  -0.00081634521484375,
  -0.0030269622802734375,
  -0.0279998779296875,
  -0.01183319091796875,
  -0.0105133056640625,
  0.0012264251708984375,
  0.016326904296875,
  0.0220947265625,
  0.03216552734375,
  -0.021331787109375,
  0.01538848876953125,
  0.01776123046875,
  0.043670654296875,
  0.034515380859375,
  0.0006985664367675781,
  0.00015556812286376953,
  -0.00743865966796875,
  0.004932403564453125,
  0.0322265625,
  -0.043212890625,
  0.0484619140625,
  -0.0031375885009765625,
  0.001972198486328125,
  -0.019500732421875,
  0.01409149169921875,
  -0.034393310546875,
  0.04541015625,
  0.009429931640625,
  0.0028018951416015625,
  -0.053497314453125,
  -0.040069580078125,
  -0.0189361572265625,
  0.0176239013671875,
  -0.0095977783203125,
  -0.0160064697265625,
  0.040740966796875,
  -0.0179901123046875,
  0.032989501953125,
  0.0044708251953125,
  -0.0169677734375,
  0.0380859375,
  0.0306854248046875,
  -0.0357666015625,
  -0.0084228515625,
  -0.0748291015625,
  0.0213623046875,
  -0.01131439208984375,
  -0.0166473388671875,
  -0.065673828125,
  0.055816650390625,
  -0.0004024505615234375,
  -0.01776123046875,
  -0.02911376953125,
  -0.0232696533203125,
  -0.0003330707550048828,
  -0.0174560546875,
  -0.0264739990234375,
  -0.00792694091796875,
  -0.03729248046875,
  -0.01012420654296875,
  -0.01306915283203125,
  -0.00917816162109375,
  -0.0020236968994140625,
  0.044525146484375,
  -0.0002512931823730469,
  -0.02728271484375,
  0.00884246826171875,
  -0.0080718994140625,
  0.01399993896484375,
  -0.028228759765625,
  0.00037550926208496094,
  0.03350830078125,
  -0.0270538330078125,
  -0.030853271484375,
  0.006267547607421875,
  0.0032196044921875,
  0.018310546875,
  0.006343841552734375,
  -0.033935546875,
  0.0248870849609375,
  -0.007450103759765625,
  0.0099945068359375,
  0.039825439453125,
  -0.032135009765625,
  0.030670166015625,
  0.0021305084228515625,
  0.00679779052734375,
  0.004032135009765625,
  -0.00738525390625,
  -0.0267486572265625,
  0.0016422271728515625,
  -0.000812530517578125,
  0.0058135986328125,
  -0.028228759765625,
  0.005756378173828125,
  0.036407470703125,
  0.0294952392578125,
  0.01522064208984375,
  0.0265045166015625,
  0.05303955078125,
  -0.034027099609375,
  6.0498714447021484e-05,
  0.0047760009765625,
  0.0160675048828125,
  -0.003925323486328125,
  0.0007777214050292969,
  0.009490966796875,
  -0.01678466796875,
  -0.02374267578125,
  0.046051025390625,
  0.0316162109375,
  0.03399658203125,
  0.030303955078125,
  -0.01235198974609375,
  -0.034149169921875,
  0.00814056396484375,
  -0.01464080810546875,
  -0.003940582275390625,
  0.042266845703125,
  -0.0147247314453125,
  -0.06634521484375,
  0.00972747802734375,
  0.0224761962890625,
  -0.0098724365234375,
  -0.01190185546875,
  0.02838134765625,
  -0.04302978515625,
  0.0203704833984375,
  -0.012847900390625,
  0.0037384033203125,
  0.06463623046875,
  -0.045989990234375,
  -0.01210784912109375,
  0.032135009765625,
  0.0158538818359375,
  -0.01078033447265625,
  -0.0478515625,
  -0.0584716796875,
  0.0321044921875,
  -0.0199127197265625,
  -0.014404296875,
  0.0055694580078125,
  -0.009765625,
  0.00508880615234375,
  -0.01264190673828125,
  0.021697998046875,
  0.001300811767578125,
  0.0216827392578125,
  -0.0283966064453125,
  -0.0107421875,
  -0.0167388916015625,
  -0.024139404296875,
  -0.0127105712890625,
  0.043914794921875,
  0.005878448486328125,
  -0.033111572265625,
  -0.0172271728515625,
  0.0182952880859375,
  0.03802490234375,
  -0.01282501220703125,
  0.01922607421875,
  -0.046539306640625,
  -0.0281524658203125,
  -0.0092010498046875,
  -0.0011548995971679688,
  0.008270263671875,
  -0.017333984375,
  -0.017120361328125,
  0.05181884765625,
  0.034759521484375,
  -0.00896453857421875,
  -0.0016937255859375,
  -0.037567138671875,
  0.04534912109375,
  0.004322052001953125,
  0.03656005859375,
  0.011322021484375,
  -0.01824951171875,
  -0.04437255859375,
  -0.01293182373046875,
  0.0301055908203125,
  0.032440185546875,
  0.01812744140625,
  -0.01277923583984375,
  -0.0220184326171875,
  -0.0207977294921875,
  0.03814697265625,
  0.0311126708984375,
  0.054290771484375,
  0.0151519775390625,
  0.0168304443359375,
  -0.0031185150146484375,
  0.012451171875,
  0.00829315185546875,
  -0.0660400390625,
  -0.0142364501953125,
  0.0206451416015625,
  -0.0294342041015625,
  0.00493621826171875,
  -0.0255584716796875,
  0.0246429443359375,
  -0.03289794921875,
  0.013427734375,
  0.0075225830078125,
  -0.00940704345703125,
  0.0231170654296875,
  0.0258941650390625,
  -0.05450439453125,
  -0.0082855224609375,
  0.01800537109375,
  0.004512786865234375,
  -0.0252227783203125,
  -0.0306854248046875,
  -0.0205535888671875,
  -0.01151275634765625,
  0.0386962890625,
  -0.01232147216796875,
  0.0007658004760742188,
  0.029144287109375,
  -0.014068603515625,
  -0.010101318359375,
  0.0058135986328125,
  -0.039276123046875,
  -0.0238800048828125,
  -0.0280914306640625,
  -0.0173797607421875,
  -0.00946807861328125,
  0.00289154052734375,
  -0.002399444580078125,
  -0.02056884765625,
  -0.01507568359375,
  0.006389617919921875,
  0.016143798828125,
  -0.033660888671875,
  0.0035953521728515625,
  -0.0193939208984375,
  0.06463623046875,
  -0.0015859603881835938,
  -0.031646728515625,
  0.005840301513671875,
  0.0162506103515625,
  -0.046356201171875,
  -0.030670166015625,
  -0.045074462890625,
  -0.01184844970703125,
  0.0158233642578125,
  -0.006275177001953125,
  0.0071563720703125,
  -0.0043487548828125,
  -0.0216827392578125,
  0.0023651123046875,
  0.01309967041015625,
  0.0172576904296875,
  -0.0494384765625,
  -0.005680084228515625,
  0.00647735595703125,
  0.00641632080078125,
  -0.01168060302734375,
  0.038818359375,
  -0.00585174560546875,
  -0.0125885009765625,
  0.025665283203125,
  -0.036102294921875,
  0.034576416015625,
  0.03997802734375,
  -0.0206756591796875,
  0.003833770751953125,
  0.021240234375,
  -0.019439697265625,
  0.0223388671875,
  8.720159530639648e-05,
  -3.975629806518555e-05,
  -0.0200653076171875,
  0.01751708984375,
  0.005588531494140625,
  -0.0099334716796875,
  -0.01221466064453125,
  -0.019775390625,
  0.006927490234375,
  -0.00241851806640625,
  0.0177764892578125,
  0.011322021484375,
  -0.021026611328125,
  -0.01018524169921875,
  -0.029541015625,
  -0.0184326171875,
  0.04290771484375,
  0.00691986083984375,
  0.0005006790161132812,
  0.03271484375,
  -0.01806640625,
  -0.00548553466796875,
  -0.00033283233642578125,
  -0.022796630859375,
  0.01534271240234375,
  -0.0168304443359375,
  -0.0178985595703125,
  0.01080322265625,
  0.023590087890625,
  -0.01328277587890625,
  0.01210784912109375,
  0.03179931640625,
  -0.062042236328125,
  -0.0271759033203125,
  -0.0111846923828125,
  0.005001068115234375,
  -0.0017499923706054688,
  0.0011968612670898438,
  0.0280914306640625,
  -0.0007944107055664062,
  0.0031604766845703125,
  -0.0394287109375,
  0.03350830078125,
  0.0296173095703125,
  -0.028472900390625,
  -0.006114959716796875,
  -0.032318115234375,
  0.0133819580078125,
  0.006595611572265625,
  0.0017299652099609375,
  0.0011987686157226562,
  0.003322601318359375,
  -0.039154052734375,
  -0.035858154296875,
  0.0157928466796875,
  -0.0236968994140625,
  -0.006561279296875,
  -0.003543853759765625,
  0.00585174560546875,
  0.00249481201171875,
  -0.01995849609375,
  0.019622802734375,
  -0.005657196044921875,
  0.01898193359375,
  -0.021820068359375,
  -0.00402069091796875,
  -0.0345458984375,
  -0.005828857421875,
  -0.007537841796875,
  0.00982666015625,
  0.029998779296875,
  0.0202789306640625,
  0.0006933212280273438,
  -0.0103607177734375,
  -0.0111083984375,
  0.04443359375,
  0.0247650146484375,
  0.038726806640625,
  -0.00019669532775878906,
  0.01361083984375,
  -0.03411865234375,
  -0.0039215087890625,
  0.00751495361328125,
  0.01038360595703125,
  0.0200347900390625,
  -0.0172119140625,
  -0.035003662109375,
  -0.0203399658203125,
  -0.0096282958984375,
  -0.00942230224609375,
  0.00695037841796875,
  0.0225677490234375,
  0.0177154541015625,
  -0.01386260986328125,
  0.003482818603515625,
  0.041168212890625,
  -0.0049896240234375,
  0.0192413330078125,
  0.05474853515625,
  -0.018463134765625,
  -0.00276947021484375,
  -0.04498291015625,
  -0.01422119140625,
  -0.00025343894958496094,
  0.01450347900390625,
  -0.005706787109375,
  0.0094757080078125,
  0.0004546642303466797,
  0.004062652587890625,
  -0.052490234375,
  -0.01369476318359375,
  0.004856109619140625,
  -0.01552581787109375,
  0.01690673828125,
  -0.0166778564453125,
  0.007373809814453125,
  0.01514434814453125,
  0.05157470703125,
  -0.040985107421875,
  -0.01293182373046875,
  -0.0047149658203125,
  0.01812744140625,
  -0.004558563232421875,
  0.04827880859375,
  0.0205078125,
  0.0207977294921875,
  0.0014486312866210938,
  -0.0186920166015625,
  -0.0357666015625,
  0.01690673828125,
  -0.01092529296875,
  -0.03265380859375,
  0.026947021484375,
  -0.00467681884765625,
  0.004486083984375,
  -0.0146484375,
  -0.01407623291015625,
  -0.0128326416015625,
  -0.0129241943359375,
  -0.023284912109375,
  -0.0046844482421875,
  -0.0018453598022460938,
  -0.0172271728515625,
  0.00467681884765625,
  -0.08843994140625,
  0.002185821533203125,
  0.00028014183044433594,
  -0.035675048828125,
  -0.00568389892578125,
  -0.0219879150390625,
  -0.0328369140625,
  -0.03424072265625,
  -0.039459228515625,
  0.0164794921875,
  0.027435302734375,
  0.004764556884765625,
  0.0157012939453125,
  -0.00231170654296875,
  0.01079559326171875,
  0.015777587890625,
  0.0142669677734375,
  0.0196533203125,
  0.00458526611328125,
  0.0045013427734375,
  -0.016357421875,
  -0.0025043487548828125,
  -0.0026569366455078125,
  -0.0093231201171875,
  -0.005401611328125,
  0.009002685546875,
  -0.0194854736328125,
  0.012359619140625,
  -0.025665283203125,
  0.0021495819091796875,
  0.0003838539123535156,
  0.02130126953125,
  0.01026153564453125,
  -0.01490020751953125,
  -0.018646240234375,
  0.005222320556640625,
  0.043975830078125,
  0.019195556640625,
  -0.007503509521484375,
  -0.0012416839599609375,
  -0.0166015625,
  -0.045806884765625,
  0.0194091796875,
  0.047027587890625,
  0.024749755859375,
  -0.00738525390625,
  0.006267547607421875,
  0.0135955810546875,
  -0.024993896484375,
  0.0281982421875,
  -0.0019435882568359375,
  0.00036597251892089844,
  0.006076812744140625,
  0.00927734375,
  0.035858154296875,
  -0.004482269287109375,
  -0.0241241455078125,
  0.0229949951171875,
  -0.016387939453125,
  0.00200653076171875,
  -0.01611328125,
  0.0028324127197265625,
  -0.03662109375,
  -0.0240020751953125,
  0.03729248046875,
  -0.01082611083984375,
  0.017669677734375,
  -0.0572509765625,
  -0.033416748046875,
  0.0221099853515625,
  0.0173187255859375,
  0.03765869140625,
  4.5359134674072266e-05,
  -0.0021572113037109375,
  0.005039215087890625,
  0.006046295166015625,
  0.0008764266967773438,
  0.0011548995971679688,
  0.0240325927734375,
  -0.01010894775390625,
  0.019561767578125,
  0.00991058349609375,
  -0.02252197265625,
  -0.00010323524475097656,
  -0.0014848709106445312,
  -0.0246429443359375,
  -0.01611328125,
  0.0203704833984375,
  0.0211029052734375,
  0.046173095703125,
  -0.01172637939453125,
  2.1755695343017578e-05,
  -0.035308837890625,
  0.006473541259765625,
  0.00579071044921875,
  0.008575439453125,
  0.0206756591796875,
  0.007785797119140625,
  -0.0055694580078125,
  0.0097198486328125,
  0.044036865234375,
  0.01548004150390625,
  -0.03997802734375,
  0.031890869140625,
  -0.0303802490234375,
  -0.002864837646484375,
  -0.016998291015625,
  -0.0289154052734375,
  0.031280517578125,
  0.00467681884765625,
  -0.011138916015625,
  0.0550537109375,
  0.005290985107421875,
  -0.005817413330078125,
  0.058197021484375,
  0.0293731689453125,
  -0.00041294097900390625,
  0.034088134765625,
  -0.0139312744140625,
  -0.024658203125,
  -0.022613525390625,
  0.00852203369140625,
  -0.005451202392578125,
  0.03326416015625,
  -0.003910064697265625,
  0.032806396484375,
  0.006572723388671875,
  0.01369476318359375,
  0.019195556640625,
  0.0137786865234375,
  0.031280517578125,
  0.00048661231994628906,
  0.0058746337890625,
  0.033905029296875,
  -0.020294189453125,
  0.0195770263671875,
  0.0288543701171875,
  -0.0091552734375,
  -0.015777587890625,
  0.0160675048828125,
  0.036376953125,
  -0.02685546875,
  0.01416778564453125,
  0.0151519775390625,
  -0.035186767578125,
  -0.0234222412109375,
  0.0250396728515625,
  -0.02679443359375,
  0.01425933837890625,
  0.00807952880859375,
  -0.0032367706298828125,
  -0.0193939208984375,
  0.00637054443359375,
  -0.058746337890625,
  -0.014617919921875,
  0.019927978515625,
  -0.002490997314453125,
  0.05645751953125,
  -0.033477783203125,
  -0.00853729248046875,
  -0.0143890380859375,
  0.0081939697265625,
  0.018585205078125,
  -0.01383209228515625,
  0.0031223297119140625,
  -0.005519866943359375,
  -0.017059326171875,
  0.051605224609375,
  -0.04541015625,
  0.031463623046875,
  -0.01012420654296875,
  -0.0209808349609375,
  0.0031757354736328125,
  -0.054473876953125,
  -0.015899658203125,
  -0.0018491744995117188,
  -0.01526641845703125,
  0.01526641845703125,
  0.0330810546875,
  0.0127410888671875,
  0.0305938720703125,
  0.0345458984375,
  0.00980377197265625,
  -0.00724029541015625,
  0.0152130126953125,
  -0.004421234130859375,
  -0.0194091796875,
  -0.004169464111328125,
  -0.0010204315185546875,
  0.0433349609375,
  0.0236663818359375,
  -0.035186767578125,
  0.03314208984375,
  -0.004596710205078125,
  0.036285400390625,
  -0.004467010498046875,
  0.004848480224609375,
  0.0088043212890625,
  0.0162353515625,
  -0.032135009765625,
  -0.042327880859375,
  0.01001739501953125,
  0.03607177734375,
  -0.01171112060546875,

In [37]:
batch_size_qdrant = 100
counter = 1
for i in range(0, len(pointstructs), batch_size_qdrant):
    batch = pointstructs[i:i + batch_size_qdrant]
    qdrant_client.upsert(
        collection_name="Amazon-reviews-collection-01",
        points=batch,
        wait=True
    )
    print(f"Processed {counter * batch_size_qdrant} of {len(pointstructs)}")
    counter += 1

Processed 100 of 137987
Processed 200 of 137987
Processed 300 of 137987
Processed 400 of 137987
Processed 500 of 137987
Processed 600 of 137987
Processed 700 of 137987
Processed 800 of 137987
Processed 900 of 137987
Processed 1000 of 137987
Processed 1100 of 137987
Processed 1200 of 137987
Processed 1300 of 137987
Processed 1400 of 137987
Processed 1500 of 137987
Processed 1600 of 137987
Processed 1700 of 137987
Processed 1800 of 137987
Processed 1900 of 137987
Processed 2000 of 137987
Processed 2100 of 137987
Processed 2200 of 137987
Processed 2300 of 137987
Processed 2400 of 137987
Processed 2500 of 137987
Processed 2600 of 137987
Processed 2700 of 137987
Processed 2800 of 137987
Processed 2900 of 137987
Processed 3000 of 137987
Processed 3100 of 137987
Processed 3200 of 137987
Processed 3300 of 137987
Processed 3400 of 137987
Processed 3500 of 137987
Processed 3600 of 137987
Processed 3700 of 137987
Processed 3800 of 137987
Processed 3900 of 137987
Processed 4000 of 137987
Processed 4100 of 137987
Processed 4200 of 137987
Processed 4300 of 137987
Processed 4400 of 137987
Processed 4500 of 137987
Processed 4600 of 137987
Processed 4700 of 137987
Processed 4800 of 137987
Processed 4900 of 137987
Processed 5000 of 137987
Processed 5100 of 137987
Processed 5200 of 137987
Processed 5300 of 137987
Processed 5400 of 137987
Processed 5500 of 137987
Processed 5600 of 137987
Processed 5700 of 137987
Processed 5800 of 137987
Processed 5900 of 137987
Processed 6000 of 137987
Processed 6100 of 137987
Processed 6200 of 137987
Processed 6300 of 137987
Processed 6400 of 137987
Processed 6500 of 137987
Processed 6600 of 137987
Processed 6700 of 137987
Processed 6800 of 137987
Processed 6900 of 137987
Processed 7000 of 137987
Processed 7100 of 137987
Processed 7200 of 137987
Processed 7300 of 137987
Processed 7400 of 137987
Processed 7500 of 137987
Processed 7600 of 137987
Processed 7700 of 137987
Processed 7800 of 137987
Processed 7900 of 137987
Processed 8000 of 137987
Processed 8100 of 137987
Processed 8200 of 137987
Processed 8300 of 137987
Processed 8400 of 137987
Processed 8500 of 137987
Processed 8600 of 137987
Processed 8700 of 137987
Processed 8800 of 137987
Processed 8900 of 137987
Processed 9000 of 137987
Processed 9100 of 137987
Processed 9200 of 137987
Processed 9300 of 137987
Processed 9400 of 137987
Processed 9500 of 137987
Processed 9600 of 137987
Processed 9700 of 137987
Processed 9800 of 137987
Processed 9900 of 137987
Processed 10000 of 137987
Processed 10100 of 137987
Processed 10200 of 137987
Processed 10300 of 137987
Processed 10400 of 137987
Processed 10500 of 137987
Processed 10600 of 137987
Processed 10700 of 137987
Processed 10800 of 137987
Processed 10900 of 137987
Processed 11000 of 137987
Processed 11100 of 137987
Processed 11200 of 137987
Processed 11300 of 137987
Processed 11400 of 137987
Processed 11500 of 137987
Processed 11600 of 137987
Processed 11700 of 137987
Processed 11800 of 137987
Processed 11900 of 137987
Processed 12000 of 137987
Processed 12100 of 137987
Processed 12200 of 137987
Processed 12300 of 137987
Processed 12400 of 137987
Processed 12500 of 137987
Processed 12600 of 137987
Processed 12700 of 137987
Processed 12800 of 137987
Processed 12900 of 137987
Processed 13000 of 137987
Processed 13100 of 137987
Processed 13200 of 137987
Processed 13300 of 137987
Processed 13400 of 137987
Processed 13500 of 137987
Processed 13600 of 137987
Processed 13700 of 137987
Processed 13800 of 137987
Processed 13900 of 137987
Processed 14000 of 137987
Processed 14100 of 137987
Processed 14200 of 137987
Processed 14300 of 137987
Processed 14400 of 137987
Processed 14500 of 137987
Processed 14600 of 137987
Processed 14700 of 137987
Processed 14800 of 137987
Processed 14900 of 137987
Processed 15000 of 137987
Processed 15100 of 137987
Processed 15200 of 137987
Processed 15300 of 137987
Processed 15400 of 137987
Processed 15500 of 137987
Processed 15600 of 137987
Processed 15700 of 137987
Processed 15800 of 137987
Processed 15900 of 137987
Processed 16000 of 137987
Processed 16100 of 137987
Processed 16200 of 137987
Processed 16300 of 137987
Processed 16400 of 137987
Processed 16500 of 137987
Processed 16600 of 137987
Processed 16700 of 137987
Processed 16800 of 137987
Processed 16900 of 137987
Processed 17000 of 137987
Processed 17100 of 137987
Processed 17200 of 137987
Processed 17300 of 137987
Processed 17400 of 137987
Processed 17500 of 137987
Processed 17600 of 137987
Processed 17700 of 137987
Processed 17800 of 137987
Processed 17900 of 137987
Processed 18000 of 137987
Processed 18100 of 137987
Processed 18200 of 137987
Processed 18300 of 137987
Processed 18400 of 137987
Processed 18500 of 137987
Processed 18600 of 137987
Processed 18700 of 137987
Processed 18800 of 137987
Processed 18900 of 137987
Processed 19000 of 137987
Processed 19100 of 137987
Processed 19200 of 137987
Processed 19300 of 137987
Processed 19400 of 137987
Processed 19500 of 137987
Processed 19600 of 137987
Processed 19700 of 137987
Processed 19800 of 137987
Processed 19900 of 137987
Processed 20000 of 137987
Processed 20100 of 137987
Processed 20200 of 137987
Processed 20300 of 137987
Processed 20400 of 137987
Processed 20500 of 137987
Processed 20600 of 137987
Processed 20700 of 137987
Processed 20800 of 137987
Processed 20900 of 137987
Processed 21000 of 137987
Processed 21100 of 137987
Processed 21200 of 137987
Processed 21300 of 137987
Processed 21400 of 137987
Processed 21500 of 137987
Processed 21600 of 137987
Processed 21700 of 137987
Processed 21800 of 137987
Processed 21900 of 137987
Processed 22000 of 137987
Processed 22100 of 137987
Processed 22200 of 137987
Processed 22300 of 137987
Processed 22400 of 137987
Processed 22500 of 137987
Processed 22600 of 137987
Processed 22700 of 137987
Processed 22800 of 137987
Processed 22900 of 137987
Processed 23000 of 137987
Processed 23100 of 137987
Processed 23200 of 137987
Processed 23300 of 137987
Processed 23400 of 137987
Processed 23500 of 137987
Processed 23600 of 137987
Processed 23700 of 137987
Processed 23800 of 137987
Processed 23900 of 137987
Processed 24000 of 137987
Processed 24100 of 137987
Processed 24200 of 137987
Processed 24300 of 137987
Processed 24400 of 137987
Processed 24500 of 137987
Processed 24600 of 137987
Processed 24700 of 137987
Processed 24800 of 137987
Processed 24900 of 137987
Processed 25000 of 137987
Processed 25100 of 137987
Processed 25200 of 137987
Processed 25300 of 137987
Processed 25400 of 137987
Processed 25500 of 137987
Processed 25600 of 137987
Processed 25700 of 137987
Processed 25800 of 137987
Processed 25900 of 137987
Processed 26000 of 137987
Processed 26100 of 137987
Processed 26200 of 137987
Processed 26300 of 137987
Processed 26400 of 137987
Processed 26500 of 137987
Processed 26600 of 137987
Processed 26700 of 137987
Processed 26800 of 137987
Processed 26900 of 137987
Processed 27000 of 137987
Processed 27100 of 137987
Processed 27200 of 137987
Processed 27300 of 137987
Processed 27400 of 137987
Processed 27500 of 137987
Processed 27600 of 137987
Processed 27700 of 137987
Processed 27800 of 137987
Processed 27900 of 137987
Processed 28000 of 137987
Processed 28100 of 137987
Processed 28200 of 137987
Processed 28300 of 137987
Processed 28400 of 137987
Processed 28500 of 137987
Processed 28600 of 137987
Processed 28700 of 137987
Processed 28800 of 137987
Processed 28900 of 137987
Processed 29000 of 137987
Processed 29100 of 137987
Processed 29200 of 137987
Processed 29300 of 137987
Processed 29400 of 137987
Processed 29500 of 137987
Processed 29600 of 137987
Processed 29700 of 137987
Processed 29800 of 137987
Processed 29900 of 137987
Processed 30000 of 137987
Processed 30100 of 137987
Processed 30200 of 137987
Processed 30300 of 137987
Processed 30400 of 137987
Processed 30500 of 137987
Processed 30600 of 137987
Processed 30700 of 137987
Processed 30800 of 137987
Processed 30900 of 137987
Processed 31000 of 137987
Processed 31100 of 137987
Processed 31200 of 137987
Processed 31300 of 137987
Processed 31400 of 137987
Processed 31500 of 137987
Processed 31600 of 137987
Processed 31700 of 137987
Processed 31800 of 137987
Processed 31900 of 137987
Processed 32000 of 137987
Processed 32100 of 137987
Processed 32200 of 137987
Processed 32300 of 137987
Processed 32400 of 137987
Processed 32500 of 137987
Processed 32600 of 137987
Processed 32700 of 137987
Processed 32800 of 137987
Processed 32900 of 137987
Processed 33000 of 137987
Processed 33100 of 137987
Processed 33200 of 137987
Processed 33300 of 137987
Processed 33400 of 137987
Processed 33500 of 137987
Processed 33600 of 137987
Processed 33700 of 137987
Processed 33800 of 137987
Processed 33900 of 137987
Processed 34000 of 137987
Processed 34100 of 137987
Processed 34200 of 137987
Processed 34300 of 137987
Processed 34400 of 137987
Processed 34500 of 137987
Processed 34600 of 137987
Processed 34700 of 137987
Processed 34800 of 137987
Processed 34900 of 137987
Processed 35000 of 137987
Processed 35100 of 137987
Processed 35200 of 137987
Processed 35300 of 137987
Processed 35400 of 137987
Processed 35500 of 137987
Processed 35600 of 137987
Processed 35700 of 137987
Processed 35800 of 137987
Processed 35900 of 137987
Processed 36000 of 137987
Processed 36100 of 137987
Processed 36200 of 137987
Processed 36300 of 137987
Processed 36400 of 137987
Processed 36500 of 137987
Processed 36600 of 137987
Processed 36700 of 137987
Processed 36800 of 137987
Processed 36900 of 137987
Processed 37000 of 137987
Processed 37100 of 137987
Processed 37200 of 137987
Processed 37300 of 137987
Processed 37400 of 137987
Processed 37500 of 137987
Processed 37600 of 137987
Processed 37700 of 137987
Processed 37800 of 137987
Processed 37900 of 137987
Processed 38000 of 137987
Processed 38100 of 137987
Processed 38200 of 137987
Processed 38300 of 137987
Processed 38400 of 137987
Processed 38500 of 137987
Processed 38600 of 137987
Processed 38700 of 137987
Processed 38800 of 137987
Processed 38900 of 137987
Processed 39000 of 137987
Processed 39100 of 137987
Processed 39200 of 137987
Processed 39300 of 137987
Processed 39400 of 137987
Processed 39500 of 137987
Processed 39600 of 137987
Processed 39700 of 137987
Processed 39800 of 137987
Processed 39900 of 137987
Processed 40000 of 137987
Processed 40100 of 137987
Processed 40200 of 137987
Processed 40300 of 137987
Processed 40400 of 137987
Processed 40500 of 137987
Processed 40600 of 137987
Processed 40700 of 137987
Processed 40800 of 137987
Processed 40900 of 137987
Processed 41000 of 137987
Processed 41100 of 137987
Processed 41200 of 137987
Processed 41300 of 137987
Processed 41400 of 137987
Processed 41500 of 137987
Processed 41600 of 137987
Processed 41700 of 137987
Processed 41800 of 137987
Processed 41900 of 137987
Processed 42000 of 137987
Processed 42100 of 137987
Processed 42200 of 137987
Processed 42300 of 137987
Processed 42400 of 137987
Processed 42500 of 137987
Processed 42600 of 137987
Processed 42700 of 137987
Processed 42800 of 137987
Processed 42900 of 137987
Processed 43000 of 137987
Processed 43100 of 137987
Processed 43200 of 137987
Processed 43300 of 137987
Processed 43400 of 137987
Processed 43500 of 137987
Processed 43600 of 137987
Processed 43700 of 137987
Processed 43800 of 137987
Processed 43900 of 137987
Processed 44000 of 137987
Processed 44100 of 137987
Processed 44200 of 137987
Processed 44300 of 137987
Processed 44400 of 137987
Processed 44500 of 137987
Processed 44600 of 137987
Processed 44700 of 137987
Processed 44800 of 137987
Processed 44900 of 137987
Processed 45000 of 137987
Processed 45100 of 137987
Processed 45200 of 137987
Processed 45300 of 137987
Processed 45400 of 137987
Processed 45500 of 137987
Processed 45600 of 137987
Processed 45700 of 137987
Processed 45800 of 137987
Processed 45900 of 137987
Processed 46000 of 137987
Processed 46100 of 137987
Processed 46200 of 137987
Processed 46300 of 137987
Processed 46400 of 137987
Processed 46500 of 137987
Processed 46600 of 137987
Processed 46700 of 137987
Processed 46800 of 137987
Processed 46900 of 137987
Processed 47000 of 137987
Processed 47100 of 137987
Processed 47200 of 137987
Processed 47300 of 137987
Processed 47400 of 137987
Processed 47500 of 137987
Processed 47600 of 137987
Processed 47700 of 137987
Processed 47800 of 137987
Processed 47900 of 137987
Processed 48000 of 137987
Processed 48100 of 137987
Processed 48200 of 137987
Processed 48300 of 137987
Processed 48400 of 137987
Processed 48500 of 137987
Processed 48600 of 137987
Processed 48700 of 137987
Processed 48800 of 137987
Processed 48900 of 137987
Processed 49000 of 137987
Processed 49100 of 137987
Processed 49200 of 137987
Processed 49300 of 137987
Processed 49400 of 137987
Processed 49500 of 137987
Processed 49600 of 137987
Processed 49700 of 137987
Processed 49800 of 137987
Processed 49900 of 137987
Processed 50000 of 137987
Processed 50100 of 137987
Processed 50200 of 137987
Processed 50300 of 137987
Processed 50400 of 137987
Processed 50500 of 137987
Processed 50600 of 137987
Processed 50700 of 137987
Processed 50800 of 137987
Processed 50900 of 137987
Processed 51000 of 137987
Processed 51100 of 137987
Processed 51200 of 137987
Processed 51300 of 137987
Processed 51400 of 137987
Processed 51500 of 137987
Processed 51600 of 137987
Processed 51700 of 137987
Processed 51800 of 137987
Processed 51900 of 137987
Processed 52000 of 137987
Processed 52100 of 137987
Processed 52200 of 137987
Processed 52300 of 137987
Processed 52400 of 137987
Processed 52500 of 137987
Processed 52600 of 137987
Processed 52700 of 137987
Processed 52800 of 137987
Processed 52900 of 137987
Processed 53000 of 137987
Processed 53100 of 137987
Processed 53200 of 137987
Processed 53300 of 137987
Processed 53400 of 137987
Processed 53500 of 137987
Processed 53600 of 137987
Processed 53700 of 137987
Processed 53800 of 137987
Processed 53900 of 137987
Processed 54000 of 137987
Processed 54100 of 137987
Processed 54200 of 137987
Processed 54300 of 137987
Processed 54400 of 137987
Processed 54500 of 137987
Processed 54600 of 137987
Processed 54700 of 137987
Processed 54800 of 137987
Processed 54900 of 137987
Processed 55000 of 137987
Processed 55100 of 137987
Processed 55200 of 137987
Processed 55300 of 137987
Processed 55400 of 137987
Processed 55500 of 137987
Processed 55600 of 137987
Processed 55700 of 137987
Processed 55800 of 137987
Processed 55900 of 137987
Processed 56000 of 137987
Processed 56100 of 137987
Processed 56200 of 137987
Processed 56300 of 137987
Processed 56400 of 137987
Processed 56500 of 137987
Processed 56600 of 137987
Processed 56700 of 137987
Processed 56800 of 137987
Processed 56900 of 137987
Processed 57000 of 137987
Processed 57100 of 137987
Processed 57200 of 137987
Processed 57300 of 137987
Processed 57400 of 137987
Processed 57500 of 137987
Processed 57600 of 137987
Processed 57700 of 137987
Processed 57800 of 137987
Processed 57900 of 137987
Processed 58000 of 137987
Processed 58100 of 137987
Processed 58200 of 137987
Processed 58300 of 137987
Processed 58400 of 137987
Processed 58500 of 137987
Processed 58600 of 137987
Processed 58700 of 137987
Processed 58800 of 137987
Processed 58900 of 137987
Processed 59000 of 137987
Processed 59100 of 137987
Processed 59200 of 137987
Processed 59300 of 137987
Processed 59400 of 137987
Processed 59500 of 137987
Processed 59600 of 137987
Processed 59700 of 137987
Processed 59800 of 137987
Processed 59900 of 137987
Processed 60000 of 137987
Processed 60100 of 137987
Processed 60200 of 137987
Processed 60300 of 137987
Processed 60400 of 137987
Processed 60500 of 137987
Processed 60600 of 137987
Processed 60700 of 137987
Processed 60800 of 137987
Processed 60900 of 137987
Processed 61000 of 137987
Processed 61100 of 137987
Processed 61200 of 137987
Processed 61300 of 137987
Processed 61400 of 137987
Processed 61500 of 137987
Processed 61600 of 137987
Processed 61700 of 137987
Processed 61800 of 137987
Processed 61900 of 137987
Processed 62000 of 137987
Processed 62100 of 137987
Processed 62200 of 137987
Processed 62300 of 137987
Processed 62400 of 137987
Processed 62500 of 137987
Processed 62600 of 137987
Processed 62700 of 137987
Processed 62800 of 137987
Processed 62900 of 137987
Processed 63000 of 137987
Processed 63100 of 137987
Processed 63200 of 137987
Processed 63300 of 137987
Processed 63400 of 137987
Processed 63500 of 137987
Processed 63600 of 137987
Processed 63700 of 137987
Processed 63800 of 137987
Processed 63900 of 137987
Processed 64000 of 137987
Processed 64100 of 137987
Processed 64200 of 137987
Processed 64300 of 137987
Processed 64400 of 137987
Processed 64500 of 137987
Processed 64600 of 137987
Processed 64700 of 137987
Processed 64800 of 137987
Processed 64900 of 137987
Processed 65000 of 137987
Processed 65100 of 137987
Processed 65200 of 137987
Processed 65300 of 137987
Processed 65400 of 137987
Processed 65500 of 137987
Processed 65600 of 137987
Processed 65700 of 137987
Processed 65800 of 137987
Processed 65900 of 137987
Processed 66000 of 137987
Processed 66100 of 137987
Processed 66200 of 137987
Processed 66300 of 137987
Processed 66400 of 137987
Processed 66500 of 137987
Processed 66600 of 137987
Processed 66700 of 137987
Processed 66800 of 137987
Processed 66900 of 137987
Processed 67000 of 137987
Processed 67100 of 137987
Processed 67200 of 137987
Processed 67300 of 137987
Processed 67400 of 137987
Processed 67500 of 137987
Processed 67600 of 137987
Processed 67700 of 137987
Processed 67800 of 137987
Processed 67900 of 137987
Processed 68000 of 137987
Processed 68100 of 137987
Processed 68200 of 137987
Processed 68300 of 137987
Processed 68400 of 137987
Processed 68500 of 137987
Processed 68600 of 137987
Processed 68700 of 137987
Processed 68800 of 137987
Processed 68900 of 137987
Processed 69000 of 137987
Processed 69100 of 137987
Processed 69200 of 137987
Processed 69300 of 137987
Processed 69400 of 137987
Processed 69500 of 137987
Processed 69600 of 137987
Processed 69700 of 137987
Processed 69800 of 137987
Processed 69900 of 137987
Processed 70000 of 137987
Processed 70100 of 137987
Processed 70200 of 137987
Processed 70300 of 137987
Processed 70400 of 137987
Processed 70500 of 137987
Processed 70600 of 137987
Processed 70700 of 137987
Processed 70800 of 137987
Processed 70900 of 137987
Processed 71000 of 137987
Processed 71100 of 137987
Processed 71200 of 137987
Processed 71300 of 137987
Processed 71400 of 137987
Processed 71500 of 137987
Processed 71600 of 137987
Processed 71700 of 137987
Processed 71800 of 137987
Processed 71900 of 137987
Processed 72000 of 137987
Processed 72100 of 137987
Processed 72200 of 137987
Processed 72300 of 137987
Processed 72400 of 137987
Processed 72500 of 137987
Processed 72600 of 137987
Processed 72700 of 137987
Processed 72800 of 137987
Processed 72900 of 137987
Processed 73000 of 137987
Processed 73100 of 137987
Processed 73200 of 137987
Processed 73300 of 137987
Processed 73400 of 137987
Processed 73500 of 137987
Processed 73600 of 137987
Processed 73700 of 137987
Processed 73800 of 137987
Processed 73900 of 137987
Processed 74000 of 137987
Processed 74100 of 137987
Processed 74200 of 137987
Processed 74300 of 137987
Processed 74400 of 137987
Processed 74500 of 137987
Processed 74600 of 137987
Processed 74700 of 137987
Processed 74800 of 137987
Processed 74900 of 137987
Processed 75000 of 137987
Processed 75100 of 137987
Processed 75200 of 137987
Processed 75300 of 137987
Processed 75400 of 137987
Processed 75500 of 137987
Processed 75600 of 137987
Processed 75700 of 137987
Processed 75800 of 137987
Processed 75900 of 137987
Processed 76000 of 137987
Processed 76100 of 137987
Processed 76200 of 137987
Processed 76300 of 137987
Processed 76400 of 137987
Processed 76500 of 137987
Processed 76600 of 137987
Processed 76700 of 137987
Processed 76800 of 137987
Processed 76900 of 137987
Processed 77000 of 137987
Processed 77100 of 137987
Processed 77200 of 137987
Processed 77300 of 137987

### A function to run search against reviews on a prefiltered set of product IDs

In [51]:
def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-reviews-collection-01",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"), # no weighting
        limit=k
    )
    
    return results

In [52]:
reviews = retrieve_prefiltered_reviews_data("bad_quality", ["B012GPCLR6"])

In [53]:
reviews.points

[ScoredPoint(id=17392, version=176, score=0.5, payload={'preprocessed_data': '🤔 I must warn you The thin is very crapy quality', 'parent_asin': 'B012GPCLR6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=121456, version=1217, score=0.33333334, payload={'preprocessed_data': 'BAD DESIGN IN THIS REGARD ONE PROBLEM - YOU HAVE TO TAKE IT APART TO CHANGE MEMORY CARDS.<br />BAD DESIGN IN THIS REGARD....<br />NICE CASE EXCEPT FOR THIS ONE PROBLEM.....', 'parent_asin': 'B012GPCLR6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=56370, version=566, score=0.25, payload={'preprocessed_data': "oh kay not great Ordered 2.  1 of the cases the thread in screw eyelets was stripped on 3 of the 4 exterior holes. Also, one of the screw eyelets where you attach the board the the base wasn't drilled out.  The other of the 2 cases was fine.  2 stars for lack of quality assurance.", 'parent_asin': 'B012GPCLR6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=79856, version=801, score=0.2, payload={'preprocessed_data': "Poor machining / poor quality control I really don't like posting bad reviews, but I was really disappointed with the case. Although it may seem a small issue to some, but the 4 screws that hold the top on are too small. Either that, or the holes that the screws are supposed to screw into were machined too big. Suffice it to say that the top isn't being held in place by anything since the screws just fall out. Hopefully, Eleduino will correct this issue.", 'parent_asin': 'B012GPCLR6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=137921, version=1382, score=0.16666667, payload={'preprocessed_data': "Nice solid case, but suffers from poor quality Purchased 12 of these cases for a work related project involving ASUS Tinker Boards.  The good news is these cases fit the Tinker Board exactly and they are fairly heavy duty and will do a good job of protecting the system.  The biggest drawback to these cases is their rather poor construction quality. Of the 12 cases purchased, 2 of them had bad fans which failed entirely and a 3rd has an iffy fan that sometimes fails to start.  This doesn't instill trust in me that the fans in the other cases will continue to work. Another problem is the bent aluminum the case is made from is fairly soft.  The four threaded screw holes for the top strip too easily.  I would gladly pay a few dollars more for this kind of case if I could be assured of higher quality, but as they are I'll probably look for another solution when building my next batch of systems.", 'parent_asin': 'B012GPCLR6'}, vector=None, shard_key=None, order_value=None)]

In [54]:
reviews = retrieve_prefiltered_reviews_data("bad quality", ["B012GPCLR6", "B0014175NE"])

In [55]:
reviews.points

[ScoredPoint(id=17392, version=176, score=0.5, payload={'preprocessed_data': '🤔 I must warn you The thin is very crapy quality', 'parent_asin': 'B012GPCLR6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=56370, version=566, score=0.33333334, payload={'preprocessed_data': "oh kay not great Ordered 2.  1 of the cases the thread in screw eyelets was stripped on 3 of the 4 exterior holes. Also, one of the screw eyelets where you attach the board the the base wasn't drilled out.  The other of the 2 cases was fine.  2 stars for lack of quality assurance.", 'parent_asin': 'B012GPCLR6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=89433, version=897, score=0.25, payload={'preprocessed_data': 'Poor quality When the item arrived I was dissapointed with the &#34;touch of red&#34; as it was barely noticable and once placed on the entertainment center it could not be seen at all.  After setting everything up, moving cords all around, and finally sitting to enjoy the new flatscreen I noticed some thick black lines.  I got up to inspect and found that it was permanent marker drawn on the screen of the television.  Yes there are ways to remove this but already being dissapointed with the color I decided to return.  The reason I gave Samsung 2 stars is for making the return process so simple, my money was refunded with no problems whatsoever.', 'parent_asin': 'B0014175NE'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=11460, version=117, score=0.2, payload={'preprocessed_data': 'Repeated quality problems, be skeptical We bought a Samsung LCD TV, LN40A650, in late 2008 for about $1200. The TV needed a repair to replace the IP Assembly within a few months ($56), and most recently replacement of the Main PCB ($356). I\'d call this a severe quality control problem at Samsung, given that we have 3 analog TV\'s still running that are over 20 years old and never required any repairs. Along with other ripoffs of the vast majority, our 2008 federal government mandated that US TV stations eliminate their analog signals, forcing viewers to "go digital" with their TV\'s, and rendering the old analog TVs obsolete unless the user installs a $50 digital-to-analog adapter (all old news, but this doesn\'t change Samsung\'s quality problem. Digital TV signals have been broadcast in the US since 1996). Digital TVs are great to watch, but keep your wallet open, especially if you buy one with this level of quality. Sorry to have to report this; seems like patriotic duty.', 'parent_asin': 'B0014175NE'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=35572, version=358, score=0.16666667, payload={'preprocessed_data': 'Good quality Greatly recommend this product to anyone, good quality.', 'parent_asin': 'B012GPCLR6'}, vector=None, shard_key=None, order_value=None)]

### Define the reviews retrieval tool

In [56]:
def get_embedding(text, model="text-embedding-3-small"):
    """因为 OpenAI Embeddings API 支持一次输入多条文本，所以返回的 data 始终是列表。当前只传入一条文本："""
    response = openai.embeddings.create(
        input=text,
        model=model
    )

    return response.data[0].embedding


def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):

    query_embedding = get_embedding(query)

    qdrant_client = QdrantClient(url="http://localhost:6333")

    results = qdrant_client.query_points(
        collection_name="Amazon-reviews-collection-01",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_data"])
        similarity_scores.append(result.score)

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
    }


def process_reviews_context(context):

    formatted_context = ""

    for id, chunk in zip(context["retrieved_context_ids"], context["retrieved_context"]):
        formatted_context += f"- ID: {id}, user review: {chunk}\n"

    return formatted_context


def get_formatted_reviews_context(query: str, parent_asins: list[str], top_k: int = 5) -> str:

    """Get the top k reviews matching a query for a list of prefiltered items.
    
    Args:
        query: The query to get the top k reviews for
        item_list: The list of item IDs to prefilter for before running the query
        top_k: The number of reviews to retrieve, this should be at least 20 if multipple items are prefiltered
    
    Returns:
        A string of the top k context chunks with IDs prepending each chunk, each representing a review for a given inventory item for a given query.
    """

    retrieved_context = retrieve_prefiltered_reviews_data(
        query,
        parent_asins,
        top_k
    )
    formatted_context = process_reviews_context(retrieved_context)

    return formatted_context

In [58]:
result = get_formatted_reviews_context("bad quality", ["B012GPCLR6", "B0014175NE"])
print(result)

- ID: B012GPCLR6, user review: 🤔 I must warn you The thin is very crapy quality
- ID: B012GPCLR6, user review: oh kay not great Ordered 2.  1 of the cases the thread in screw eyelets was stripped on 3 of the 4 exterior holes. Also, one of the screw eyelets where you attach the board the the base wasn't drilled out.  The other of the 2 cases was fine.  2 stars for lack of quality assurance.
- ID: B0014175NE, user review: Poor quality When the item arrived I was dissapointed with the &#34;touch of red&#34; as it was barely noticable and once placed on the entertainment center it could not be seen at all.  After setting everything up, moving cords all around, and finally sitting to enjoy the new flatscreen I noticed some thick black lines.  I got up to inspect and found that it was permanent marker drawn on the screen of the television.  Yes there are ways to remove this but already being dissapointed with the color I decided to return.  The reason I gave Samsung 2 stars is for making the return process so simple, my money was refunded with no problems whatsoever.
- ID: B0014175NE, user review: Repeated quality problems, be skeptical We bought a Samsung LCD TV, LN40A650, in late 2008 for about $1200. The TV needed a repair to replace the IP Assembly within a few months ($56), and most recently replacement of the Main PCB ($356). I'd call this a severe quality control problem at Samsung, given that we have 3 analog TV's still running that are over 20 years old and never required any repairs. Along with other ripoffs of the vast majority, our 2008 federal government mandated that US TV stations eliminate their analog signals, forcing viewers to "go digital" with their TV's, and rendering the old analog TVs obsolete unless the user installs a $50 digital-to-analog adapter (all old news, but this doesn't change Samsung's quality problem. Digital TV signals have been broadcast in the US since 1996). Digital TVs are great to watch, but keep your wallet open, especially if you buy one with this level of quality. Sorry to have to report this; seems like patriotic duty.
- ID: B012GPCLR6, user review: Good quality Greatly recommend this product to anyone, good quality.